name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    container:
      image: maven:3-openjdk-17

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: mvn clean test
